name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  check_suite:
    types: [completed]
Í
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Dependabot PRs automatically
        uses: jo-sm/at-dependabot-merge@v1.3.1
        with:
          token: ${{ secrets.DEPENDABOT_AUTO_MERGE_TOKEN }}
